Controllers/AnalyticsController.cs
using Microsoft.AspNetCore.Mvc;
using MyCinema.Services.IServices;
using MyCinema.ViewModels;
using X.PagedList;
using X.PagedList.Extensions;

namespace MyCinema.Controllers
{
    public class AnalyticsController : Controller
    {
        private readonly IAnalyticsService _analyticsService;
        public AnalyticsController(IAnalyticsService analyticsService)
        {
            _analyticsService = analyticsService;
        }

        public async Task<IActionResult> Index([FromQuery] string fromDate, [FromQuery] string toDate)
        {
            fromDate ??= DateTime.Now.AddDays(-7).ToString();
            toDate ??= DateTime.Now.AddDays(0).ToString();
            DateTime from = DateTime.Parse(fromDate);
            DateTime to = DateTime.Parse(toDate);
            var data = await _analyticsService.MapPaymentsForPeriodToAnalyticsIndexViewModel(from, to);
            return View(data);
        }
        public async Task<IActionResult> Movie()
        {
            var model = await _analyticsService.GetAnalyticsMovieViewModels(DateTime.MinValue, DateTime.MaxValue);
            return View(model);
        }
        public async Task<IActionResult> Payments(int? page)
        {
            int pageSize = 10;
            int pageNumber = (page ?? 1);

            var (data, totalCount) = await _analyticsService.GetPaymentAnalyticsViewModelsAsync(pageNumber);


            var pagedList = new StaticPagedList<PaymentAnalyticsViewModel>(data, pageNumber, pageSize, totalCount);

            return View(pagedList);
        }

    }
}

Controllers/SalonController.cs
using System.Drawing;
using System.Runtime.InteropServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.DotNet.Scaffolding.Shared.Messaging;
using MyCinema.Data;
using MyCinema.Helpers;
using MyCinema.Services;
using MyCinema.Services.IServices;

namespace MyCinema.Controllers
{
    [Authorize(Roles = "Admin")]
    public class SalonController : Controller
    {
        private readonly ISalonService _salonService;
        public SalonController(ISalonService salonService)
        {
            _salonService = salonService;
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult AddSalon()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddSalon(TheatreSalon salon, string EmptySeatsCoords)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await _salonService.AddSalonAsync(salon, EmptySeatsCoords);
                    return RedirectToAction("Index");
                }
                catch (ArgumentException ex)
                {
                    ModelState.AddModelError("SalonNumber", ex.Message);
                }
            }
            return RedirectToAction("AddSalon");
        }

        public async Task<IActionResult> Salons()
        {
            var salons = await _salonService.GetTheatreSalonsAsync();
            return View(salons);
        }
        public async Task<IActionResult> SalonDetails(Guid Id)
        {
            return View(await _salonService.GetTheatreSalonByIdAsync(Id));
        }
        public async Task<IActionResult> MovieTimelines([FromQuery] QueryObject query)
        {
            if (query.Date == null)
            {
                query.Date = DateTime.Now;
            }
            var model = await _salonService.GetSalonMovieTimelineViewModels(query);
            if (model == null || model.Count == 0)
            {
                return NotFound();
            }

            ViewBag.CinemaOpenTime = model[0].CinemaOpenTime;//< model[0].CinemaCloseTime ? model[0].CinemaOpenTime : model[0].CinemaCloseTime;
            ViewBag.CinemaCloseTime = (model[0].CinemaCloseTime); //> model[0].CinemaCloseTime? model[0].CinemaOpenTime: model[0].CinemaCloseTime).Add(TimeSpan.FromHours(1));

            return View(model);
        }
    }
}

Controllers/TicketController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyCinema.Data;
using MyCinema.Services.IServices;
using MyCinema.ViewModels;
using Stripe.Checkout;

namespace MyCinema.Controllers
{
    public class TicketController : Controller
    {
        private readonly ITicketService _ticketService;
        public TicketController(ITicketService ticketService)
        {
            _ticketService = ticketService;
        }
        public IActionResult Index()
        {
            return View();
        }
        public async Task<IActionResult> SelectTicket(Guid id)
        {
            var SelectTicketViewModel = await _ticketService.GetSelectTicketViewModel(id);
            return View(SelectTicketViewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SelectTicket(SelectTicketViewModel model)
        {
            if(ModelState.IsValid)
            {
                var TicketId = await _ticketService.AddTicketOwnershipInDbAsync(model);
                return RedirectToAction("SelectSeats", new { Id = TicketId });
            }
            var SelectTicketViewModel = await _ticketService.GetSelectTicketViewModel(model.ScreeningId);
            return View(SelectTicketViewModel);
        }
        public async Task<IActionResult> SelectSeats(Guid id)
        {
            await _ticketService.UnSeedSeatsCoordsWithTicketOrder(id);
            var model = await _ticketService.GetSelectSeatsViewModel(id);
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SelectSeats(SelectSeatsViewModel model)
        {
            if (ModelState.IsValid)
            {
                await _ticketService.SeedSeatsCoordsWithTicketOrder(model);
                return RedirectToAction("ConfirmOrder", new { Id = model.TicketOrderId });
            }
            return View();
        }
        public async Task<IActionResult> ConfirmOrder(Guid Id) 
        {
            var model = await _ticketService.GetConfirmOrderViewModel(Id);
            if (model == null)
            {
                return RedirectToAction("Index", "Movie");
            }
            if (model.RegularTicketSeatsCoords.Contains("-1") || model.VipTicketSeatsCoords.Contains("-1"))
            {
                return RedirectToAction("SelectSeats", new { id = Id });
            }
            return View(model);
        }
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ConfirmOrder(ConfirmOrderViewModel model)
        {
            if (ModelState.IsValid)
            {
                var OrderId = model.TicketOrderId;
                if (await _ticketService.IsTicketOrderExists(OrderId) == false)
                {
                    return RedirectToAction("Index");
                }
                var session = await _ticketService.CreateStripeSession(OrderId);
                return Redirect(session.Url);
            }
            return View(model);
        }
        public async Task<IActionResult> Success([FromQuery]Guid OrderId)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            await _ticketService.ConfirmTicketOrder(OrderId, userId);
            return RedirectToAction("Index","Movie");
        }
        public IActionResult Cancel([FromQuery]Guid OrderId)
        {
            return RedirectToAction("ConfirmOrder" , new {Id=OrderId });
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyCinema</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyCinema.styles.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">

</head>
<body>
    <!-- Navigation Bar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">MyCinema</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item"><a href="@Url.Action("Index", "Movie")" class="nav-link active">Screenings</a></li>
                    <li class="nav-item"><a href="@Url.Action("Index", "AboutUs")" class="nav-link">About us</a></li>

                    @if (User.IsInRole("Admin"))
                    {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="adminDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Admin Panel</a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="@Url.Action("Salons", "Salon")">View Salons</a></li>
                                <li><a class="dropdown-item" href="@Url.Action("AddSalon", "Salon")">Add Salon</a></li>
                                <li><a class="dropdown-item" href="@Url.Action("MovieTimelines", "Salon")">All Screenings</a></li>
                                <li><a class="dropdown-item" href="@Url.Action("NowPlaying", "Movie")">Now Playing</a></li>
                                <li><a class="dropdown-item" href="@Url.Action("MovieList", "Movie")">Movies in Db</a></li>
                                <li><a class="dropdown-item" href="@Url.Action("CreateScreening", "Screening")">Add Screening</a></li>
                                <li><a class="dropdown-item" href="@Url.Action("Index", "Analytics")">Analytics Overview</a></li>
                                <li><a class="dropdown-item" href="@Url.Action("Index", "Admin")">Admin Panel</a></li>
                            </ul>
                        </li>
                    }
                </ul>

                <!-- Search Bar -->
                <form class="d-flex align-items-center me-4" action="@Url.Action("Search", "Movie")" method="get">
                    <div class="position-relative">
                        <input class="form-control ps-4 pe-5 rounded-pill shadow-sm" type="search" placeholder="Search..." aria-label="Search" name="query" style="width: 200px; height: 36px;">
                        <button class="btn position-absolute end-0 top-50 translate-middle-y me-2 p-0 border-0 bg-transparent text-primary" type="submit">
                            <i class="bi bi-search"></i>
                        </button>
                    </div>
                </form>


                <!-- Login Partial -->
                <div class="d-flex">
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </div>
    </nav>

    <!-- Main content -->
    <div class="container mt-4">
        <div class="pb-3">
            @RenderBody()
        </div>
        <footer class="text-center py-3">
            <span class="text-muted">&copy; 2024 MyCinema</span>
        </footer>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation/1.19.5/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.12/jquery.validate.unobtrusive.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_ScreeningsPartial.cshtml
@if(Model.Screenings.Count!=0){
        @foreach (var screening in Model.Screenings)
        {
            <a href="@Url.Action("SelectTicket","Ticket", new {id = screening.Id})" class="btn btn-outline-primary">
                @screening.StartTime.ToString("HH:mm")
            </a>
        }
}
else{

    <p class="text-muted">No screenings available for this date.</p>

}

Views/Shared/_movieListPartial.cshtml
@model IEnumerable<MyCinema.ViewModels.MovieListViewModel>

@{
    var currentPage = ViewBag.CurrentPage ?? 1;
    var totalPages = ViewBag.TotalPages ?? 1;

    int maxPagesToShow = 10;
    int startPage = Math.Max(1, (int)currentPage - maxPagesToShow / 2);
    int endPage = Math.Min((int)totalPages, (int)currentPage + maxPagesToShow / 2);
}
        <table class="table table-bordered table-striped table-hover">
            <thead class="table-dark">
                <tr>
                    <th scope="col">
                            <input type="checkbox" id="select-all" onclick="toggleSelectAll(this)">
                        </th>
                    <th scope="col">#</th>
                    <th scope="col">id</th>
                    <th scope="col">Title</th>
                    <th scope="col">Release date</th>
                    <th scope="col">Original Lang</th>
                    <th scope="col">Adult?</th>
                    <th scope="col">Vote average</th>
                    <th scope="col">Vote Count</th>
                </tr>
            </thead>
            <tbody>
                @if (Model != null && Model.Any())
                {
                    int index = 1;
                    foreach (var movie in Model)
                    {
                                                           <tr style="cursor:pointer" onclick="window.location.href='@Url.Action("Details", "Movie", new { id = movie.id })'">
                                                            <td>
                                                                                        <input type="checkbox" name="selectedMovies" value="@movie.id" class="movie-checkbox"  onclick="event.stopPropagation(); updateButtonState();">
                                                            </td>
                                                            <th scope="row">@index</th>
                                                            <td>@movie.moviedbId</td>
                                                            <td>@movie.Title</td>
                                                            <td>@movie.Release_date</td>
                                                            <td>@movie.Original_language</td>
                                                            <td>@movie.Adult</td>
                                                            <td>@movie.Vote_average</td>
                                                            <td>@movie.Vote_count</td>
                                                        </tr>
                        index++;
                    }
                }
                else
                {
                                    <tr>
                                        <td colspan="6" class="text-center">No movies available.</td>
                                    </tr>
                }
            </tbody>
        </table>